FROM codeclimate/codeclimate-gnu-complexity
USER root
RUN DEBIAN_FRONTEND=noninteractive && \
  apt-get update -y -q && \
  apt-get install -y -q \
    python-setuptools \
    python-dev \
    build-essential && \
  easy_install pip && \
  pip install --upgrade pip && \
  pip install cram
COPY test /test
WORKDIR /test
CMD ["cram", "/test"]
